//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalProject.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource1() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FinalProject.Resources.Resource1", typeof(Resource1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Address1 {
            get {
                return ResourceManager.GetString("Address1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address:.
        /// </summary>
        public static string AddressLabel {
            get {
                return ResourceManager.GetString("AddressLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to Cart.
        /// </summary>
        public static string AddToCart {
            get {
                return ResourceManager.GetString("AddToCart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to Cart.
        /// </summary>
        public static string AddToCartButton {
            get {
                return ResourceManager.GetString("AddToCartButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bangla.
        /// </summary>
        public static string Bangla {
            get {
                return ResourceManager.GetString("Bangla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cart.
        /// </summary>
        public static string Cart {
            get {
                return ResourceManager.GetString("Cart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cart is empty.
        /// </summary>
        public static string CartIsEmpty {
            get {
                return ResourceManager.GetString("CartIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories.
        /// </summary>
        public static string Categories {
            get {
                return ResourceManager.GetString("Categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Language.
        /// </summary>
        public static string ChangeLanguage {
            get {
                return ResourceManager.GetString("ChangeLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checkout.
        /// </summary>
        public static string Checkout {
            get {
                return ResourceManager.GetString("Checkout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checkout.
        /// </summary>
        public static string Checkout1 {
            get {
                return ResourceManager.GetString("Checkout1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password:.
        /// </summary>
        public static string ConfirmPasswordLabel {
            get {
                return ResourceManager.GetString("ConfirmPasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Us.
        /// </summary>
        public static string ContactUsButton {
            get {
                return ResourceManager.GetString("ContactUsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyrights.
        /// </summary>
        public static string Copyrights {
            get {
                return ResourceManager.GetString("Copyrights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go To Dashboard.
        /// </summary>
        public static string Dashboard {
            get {
                return ResourceManager.GetString("Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of Birth:.
        /// </summary>
        public static string DateOfBirthLabel {
            get {
                return ResourceManager.GetString("DateOfBirthLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hikan Strawberry.
        /// </summary>
        public static string DealOfTheMonthProduct {
            get {
                return ResourceManager.GetString("DealOfTheMonthProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deal of the month.
        /// </summary>
        public static string DealOfTheMonthTitle {
            get {
                return ResourceManager.GetString("DealOfTheMonthTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get December Discount.
        /// </summary>
        public static string decdes {
            get {
                return ResourceManager.GetString("decdes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery Option.
        /// </summary>
        public static string DeliveryOption {
            get {
                return ResourceManager.GetString("DeliveryOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email:.
        /// </summary>
        public static string EmailLabel {
            get {
                return ResourceManager.GetString("EmailLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name:.
        /// </summary>
        public static string FirstNameLabel {
            get {
                return ResourceManager.GetString("FirstNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When order over $75.
        /// </summary>
        public static string FreeShippingDescription {
            get {
                return ResourceManager.GetString("FreeShippingDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free Shipping.
        /// </summary>
        public static string FreeShippingTitle {
            get {
                return ResourceManager.GetString("FreeShippingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fruit Collection.
        /// </summary>
        public static string FruitCollectionButton {
            get {
                return ResourceManager.GetString("FruitCollectionButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go back.
        /// </summary>
        public static string GoBack {
            get {
                return ResourceManager.GetString("GoBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fresh &amp; Organic.
        /// </summary>
        public static string HomeSlider1Subtitle {
            get {
                return ResourceManager.GetString("HomeSlider1Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delicious Seasonal Fruits.
        /// </summary>
        public static string HomeSlider1Title {
            get {
                return ResourceManager.GetString("HomeSlider1Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fresh Everyday.
        /// </summary>
        public static string HomeSlider2Subtitle {
            get {
                return ResourceManager.GetString("HomeSlider2Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 100% Organic Collection.
        /// </summary>
        public static string HomeSlider2Title {
            get {
                return ResourceManager.GetString("HomeSlider2Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inside Dhaka.
        /// </summary>
        public static string InsideDhaka {
            get {
                return ResourceManager.GetString("InsideDhaka", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to know more.
        /// </summary>
        public static string know {
            get {
                return ResourceManager.GetString("know", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name:.
        /// </summary>
        public static string LastNameLabel {
            get {
                return ResourceManager.GetString("LastNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login1 {
            get {
                return ResourceManager.GetString("Login1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string LoginButton {
            get {
                return ResourceManager.GetString("LoginButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string LoginLinkText {
            get {
                return ResourceManager.GetString("LoginLinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mega Sale Going On!.
        /// </summary>
        public static string mega {
            get {
                return ResourceManager.GetString("mega", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More News.
        /// </summary>
        public static string News {
            get {
                return ResourceManager.GetString("News", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You will vainly look for fruit....
        /// </summary>
        public static string NewsTitle1 {
            get {
                return ResourceManager.GetString("NewsTitle1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A man&apos;s worth has its season....
        /// </summary>
        public static string NewsTitle2 {
            get {
                return ResourceManager.GetString("NewsTitle2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Good thoughts bear good....
        /// </summary>
        public static string NewsTitle3 {
            get {
                return ResourceManager.GetString("NewsTitle3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orders.
        /// </summary>
        public static string Orders {
            get {
                return ResourceManager.GetString("Orders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outside Dhaka.
        /// </summary>
        public static string OutsideDhaka {
            get {
                return ResourceManager.GetString("OutsideDhaka", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string PageTitle {
            get {
                return ResourceManager.GetString("PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password:.
        /// </summary>
        public static string PasswordLabel {
            get {
                return ResourceManager.GetString("PasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Per Kg / Piece.
        /// </summary>
        public static string PerKg {
            get {
                return ResourceManager.GetString("PerKg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number:.
        /// </summary>
        public static string PhoneNumberLabel {
            get {
                return ResourceManager.GetString("PhoneNumberLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here Popular product is Dynamic....
        /// </summary>
        public static string PopularProductsDescription {
            get {
                return ResourceManager.GetString("PopularProductsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Popular Products.
        /// </summary>
        public static string PopularProductsTitle {
            get {
                return ResourceManager.GetString("PopularProductsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product.
        /// </summary>
        public static string Product {
            get {
                return ResourceManager.GetString("Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get refund within 3 days!.
        /// </summary>
        public static string RefundDescription {
            get {
                return ResourceManager.GetString("RefundDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refund.
        /// </summary>
        public static string RefundTitle {
            get {
                return ResourceManager.GetString("RefundTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Register1 {
            get {
                return ResourceManager.GetString("Register1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string RegisterButton {
            get {
                return ResourceManager.GetString("RegisterButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string RegisterLinkText {
            get {
                return ResourceManager.GetString("RegisterLinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t have an account?.
        /// </summary>
        public static string RegisterPrompt {
            get {
                return ResourceManager.GetString("RegisterPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already have an account?.
        /// </summary>
        public static string RegisterPrompt1 {
            get {
                return ResourceManager.GetString("RegisterPrompt1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to , All Rights Reserved..
        /// </summary>
        public static string Reserved {
            get {
                return ResourceManager.GetString("Reserved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search For:.
        /// </summary>
        public static string SearchFor {
            get {
                return ResourceManager.GetString("SearchFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See more Details.
        /// </summary>
        public static string SeeMoreDetails {
            get {
                return ResourceManager.GetString("SeeMoreDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share.
        /// </summary>
        public static string Share {
            get {
                return ResourceManager.GetString("Share", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shefain.
        /// </summary>
        public static string Shefain {
            get {
                return ResourceManager.GetString("Shefain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipping.
        /// </summary>
        public static string Shipping {
            get {
                return ResourceManager.GetString("Shipping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shop Now.
        /// </summary>
        public static string ShopNowButton {
            get {
                return ResourceManager.GetString("ShopNowButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single Product.
        /// </summary>
        public static string SingleProduct {
            get {
                return ResourceManager.GetString("SingleProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subtotal.
        /// </summary>
        public static string Subtotal {
            get {
                return ResourceManager.GetString("Subtotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get support all day.
        /// </summary>
        public static string SupportDescription {
            get {
                return ResourceManager.GetString("SupportDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 24/7 Support.
        /// </summary>
        public static string SupportTitle {
            get {
                return ResourceManager.GetString("SupportTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I accept the terms and conditions.
        /// </summary>
        public static string TermsLabel {
            get {
                return ResourceManager.GetString("TermsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our News.
        /// </summary>
        public static string TestimonialsTitle {
            get {
                return ResourceManager.GetString("TestimonialsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        public static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visit Shop.
        /// </summary>
        public static string VisitShopButton {
            get {
                return ResourceManager.GetString("VisitShopButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to.
        /// </summary>
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
    }
}
